import { pool } from "../../common/db.js";
import { applyBalanceDelta, getPlatformWalletId, getUserWalletId, insertEntry } from "../../common/ledger.js";
import { notify } from "../../notifications/service.js";
import { chapaPayoutClient } from "../chapa-client.js";
import { consumeClearedEarningHoldsForPayout, restoreEarningHoldsForPayout } from "../earning-holds-service.js";
import { decryptPayoutInstrumentAccountNumber } from "../payout-instruments-service.js";
import type { PayoutWorkflowInput } from "./types.js";

// Every activity here wraps the exact same DB/Chapa logic
// wallet/service.ts's original inline requestPayout/approvePayout already
// used — the business logic isn't new, only its packaging is. Each one is
// written to be safely retryable (Temporal's execution model is
// at-least-once per activity, not exactly-once), since a network blip
// between an activity completing and Temporal recording that completion
// means the same activity call can run again.

// Idempotent via the payouts table's primary key: payoutId is generated by
// the caller (wallet/service.ts) before the workflow starts and reused as
// the row's id — a retried reserveFunds hits a primary-key conflict on the
// second attempt instead of double-reserving funds, and returns the
// already-reserved row instead of erroring.
export async function reserveFunds(input: PayoutWorkflowInput): Promise<{ payoutId: string }> {
  const existing = await pool.query<{ id: string }>(`SELECT id FROM payouts WHERE id = $1`, [input.payoutId]);
  if (existing.rows[0]) {
    return { payoutId: input.payoutId };
  }

  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    const creatorWalletId = await getUserWalletId(client, input.creatorId);
    const platformWalletId = await getPlatformWalletId(client);

    // method/bank_code are denormalized from the instrument at reservation
    // time (same "pin it at time of send" reasoning as T3's gifts_sent.
    // creator_share_bps) — a later change to the instrument (or its
    // retirement) must never rewrite what a past payout actually used.
    const { rows: instrumentRows } = await client.query<{ method: string; bank_code: string | null }>(
      `SELECT method, bank_code FROM payout_instruments WHERE id = $1 AND creator_id = $2`,
      [input.instrumentId, input.creatorId]
    );
    const instrument = instrumentRows[0];
    if (!instrument) throw new Error(`Unknown or mismatched payout instrument ${input.instrumentId}`);

    const { rows } = await client.query<{ id: string }>(
      `INSERT INTO ledger_transactions (type, status, completed_at) VALUES ('payout', 'completed', now()) RETURNING id`
    );
    const ledgerTransactionId = rows[0]!.id;

    const status = input.requiresManualApproval ? "pending_review" : "processing";
    await client.query(
      `INSERT INTO payouts (id, ledger_transaction_id, creator_id, amount_santim, method, bank_code, instrument_id, status, requires_manual_approval)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        input.payoutId,
        ledgerTransactionId,
        input.creatorId,
        input.amountSantim,
        instrument.method,
        instrument.bank_code,
        input.instrumentId,
        status,
        input.requiresManualApproval,
      ]
    );

    // The real eligibility gate: withdrawable is cleared earning_holds, not
    // wallet_balances_cache's pooled total (which also holds pending and
    // promotional money) — see wallet/earning-holds-service.ts. Throws
    // "Insufficient withdrawable balance" if short, which rolls back the
    // payouts/ledger_transactions inserts above along with everything else.
    await consumeClearedEarningHoldsForPayout(client, input.creatorId, input.amountSantim, input.payoutId);

    await insertEntry(client, ledgerTransactionId, creatorWalletId, "debit", input.amountSantim);
    await insertEntry(client, ledgerTransactionId, platformWalletId, "credit", input.amountSantim);
    await applyBalanceDelta(client, creatorWalletId, -input.amountSantim);
    await applyBalanceDelta(client, platformWalletId, input.amountSantim);

    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK");
    throw err;
  } finally {
    client.release();
  }

  return { payoutId: input.payoutId };
}

export async function markApproved(payoutId: string, adminUserId: string): Promise<void> {
  await pool.query(`UPDATE payouts SET approved_by = $1, status = 'processing' WHERE id = $2`, [
    adminUserId,
    payoutId,
  ]);
}

// Reverses a payout's ledger effect and marks it failed — idempotent by
// checking current status first (mirrors completePayoutFromWebhook's
// existing idempotency check in the pre-Temporal code), since a retried
// call after a crash between the DB write and Temporal recording it must
// not double-refund the creator.
export async function reverseFunds(payoutId: string, failureReason: string): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    const { rows } = await client.query<{ creator_id: string; amount_santim: number; status: string }>(
      `SELECT creator_id, amount_santim, status FROM payouts WHERE id = $1 FOR UPDATE`,
      [payoutId]
    );
    const payout = rows[0];
    if (!payout) throw new Error(`Unknown payout ${payoutId}`);
    if (payout.status === "failed" || payout.status === "paid") {
      await client.query("COMMIT");
      return;
    }

    const creatorWalletId = await getUserWalletId(client, payout.creator_id);
    const platformWalletId = await getPlatformWalletId(client);
    const { rows: txRows } = await client.query<{ id: string }>(
      `INSERT INTO ledger_transactions (type, status, completed_at) VALUES ('refund', 'completed', now()) RETURNING id`
    );
    const reversalId = txRows[0]!.id;
    await insertEntry(client, reversalId, creatorWalletId, "credit", payout.amount_santim);
    await insertEntry(client, reversalId, platformWalletId, "debit", payout.amount_santim);
    await applyBalanceDelta(client, creatorWalletId, payout.amount_santim);
    await applyBalanceDelta(client, platformWalletId, -payout.amount_santim);

    await client.query(`UPDATE payouts SET status = 'failed', failure_reason = $1 WHERE id = $2`, [
      failureReason,
      payoutId,
    ]);
    await client.query("COMMIT");

    await notify(payout.creator_id, "payout_failed", "Your payout failed", {
      body: "It's been refunded to your wallet balance — check Wallet for details",
      linkUrl: "/wallet",
    });
  } catch (err) {
    await client.query("ROLLBACK");
    throw err;
  } finally {
    client.release();
  }
}

// Chapa's transfer reference is the payoutId itself (same as the original
// inline code) — assumed idempotent on Chapa's side for retried calls with
// the same reference, inherited from the pre-Temporal implementation's own
// assumption (see wallet/service.ts's original requestPayout), not
// independently re-verified against Chapa's docs in this pass.
//
// The only place in this entire workflow that ever sees the decrypted
// account number — fetched fresh from payout_instruments right here,
// never carried in the workflow's own input (see types.ts's comment).
export async function initiateChapaTransfer(input: {
  payoutId: string;
  instrumentId: string;
  accountName: string;
  amountSantim: number;
}): Promise<{ chapaReference: string }> {
  const existing = await pool.query<{ chapa_reference: string | null }>(
    `SELECT chapa_reference FROM payouts WHERE id = $1`,
    [input.payoutId]
  );
  if (existing.rows[0]?.chapa_reference) {
    return { chapaReference: existing.rows[0].chapa_reference };
  }

  const { rows } = await pool.query<{ bank_code: string | null }>(
    `SELECT bank_code FROM payout_instruments WHERE id = $1`,
    [input.instrumentId]
  );
  const bankCode = rows[0]?.bank_code;
  if (!bankCode) throw new Error(`Payout instrument ${input.instrumentId} has no bank_code`);
  const accountNumber = await decryptPayoutInstrumentAccountNumber(input.instrumentId);

  const { chapaReference } = await chapaPayoutClient.initiateTransfer({
    accountNumber,
    accountName: input.accountName,
    amountSantim: input.amountSantim,
    bankCode,
    reference: input.payoutId,
  });
  await pool.query(`UPDATE payouts SET chapa_reference = $1 WHERE id = $2`, [chapaReference, input.payoutId]);
  return { chapaReference };
}

export async function markPaid(payoutId: string, amountSantim: number, creatorId: string): Promise<void> {
  const { rows } = await pool.query<{ status: string }>(`SELECT status FROM payouts WHERE id = $1`, [payoutId]);
  if (rows[0]?.status === "paid") return; // already recorded — retried call, no-op
  await pool.query(`UPDATE payouts SET status = 'paid', paid_at = now() WHERE id = $1`, [payoutId]);
  await notify(creatorId, "payout_processed", "Your payout was sent", {
    body: `${(amountSantim / 100).toFixed(2)} birr is on its way`,
    linkUrl: "/wallet",
  });
}

