// Shared between workflow.ts and activities.ts — workflow code runs in
// Temporal's deterministic sandbox and can only import plain types/values,
// never Node built-ins or the rest of this app's modules directly (that's
// what proxyActivities in workflow.ts is for), so this file stays free of
// any non-type imports.

export interface PayoutWorkflowInput {
  payoutId: string; // generated by the caller, also used as the Temporal workflow ID — see client.ts's comment on why that's the idempotency mechanism.
  creatorId: string;
  amountSantim: number;
  method: "telebirr" | "bank";
  destination: string;
  bankCode: string;
  displayName: string;
  requiresManualApproval: boolean;
}

export type PayoutWorkflowStatus = "processing" | "paid" | "failed";

export interface PayoutWorkflowResult {
  status: PayoutWorkflowStatus;
  failureReason?: string;
}

export interface RejectPayoutSignal {
  adminUserId: string;
  reason: string;
}

export interface ApprovePayoutSignal {
  adminUserId: string;
}

export interface ChapaTransferOutcomeSignal {
  success: boolean;
  reason?: string;
}
