// Shared between workflow.ts and activities.ts — workflow code runs in
// Temporal's deterministic sandbox and can only import plain types/values,
// never Node built-ins or the rest of this app's modules directly (that's
// what proxyActivities in workflow.ts is for), so this file stays free of
// any non-type imports.

export interface PayoutWorkflowInput {
  payoutId: string; // generated by the caller, also used as the Temporal workflow ID — see client.ts's comment on why that's the idempotency mechanism.
  creatorId: string;
  amountSantim: number;
  // T7: replaces method/destination/bankCode. The instrument's account
  // number must NEVER be a workflow input field — Temporal durably
  // persists every workflow input in its own event history, so passing
  // decrypted plaintext through here would defeat encrypting it at rest
  // in payout_instruments in the first place. Only initiateChapaTransfer
  // (activities.ts) ever decrypts it, fetched fresh at the moment it's
  // actually needed.
  instrumentId: string;
  displayName: string;
  requiresManualApproval: boolean;
}

export type PayoutWorkflowStatus = "processing" | "paid" | "failed";

export interface PayoutWorkflowResult {
  status: PayoutWorkflowStatus;
  failureReason?: string;
}

export interface RejectPayoutSignal {
  adminUserId: string;
  reason: string;
}

export interface ApprovePayoutSignal {
  adminUserId: string;
}

export interface ChapaTransferOutcomeSignal {
  success: boolean;
  reason?: string;
}
